Update configuration variable management
Update script to use backup.sh owner to run backup script; change default path to backup.sh to use trmm-supplied script (no more manual download); perform basic sanity checks on all configuration variables.

diff --git a/trmmcronbackup b/trmmcronbackup
--- a/trmmcronbackup
+++ b/trmmcronbackup
@@ -9,10 +9,10 @@
 # License:  GPL 2.0 or newer
 
 # Configuration Variables
-BACKUP_COUNT=8
-SCRIPT_USER=tactical
-PATH_TO_SCRIPT=/home/tactical/backup.sh
-PATH_TO_BACKUPS=/rmmbackups
+BACKUP_COUNT=8                  # Number of backups to keep
+PATH_TO_SCRIPT=/rmm/backup.sh   # Path to backup script
+#SCRIPT_USER=tactical           # Script to run (unset: use script owner)
+PATH_TO_BACKUPS=/rmmbackups     # Path to backup destination
 VERBOSE=FALSE                   # Use TRUE for verbose output
 
 # Script begins below
@@ -20,8 +20,41 @@ vecho() {  # Echo only if user specifies Verbose output
     if [[ "${VERBOSE}" == "TRUE" ]]; then echo "${1}"; fi
 }
 
+# Check the configuration variables
+vecho "Initial configuration variables:"
+vecho "-- BACKUP_COUNT:  ${BACKUP_COUNT}"
+case ${BACKUP_COUNT} in
+    ''|*[!0-9]*) # Make sure variable is a number
+        echo "Bad BACKUP_COUNT:  ${BACKUP_COUNT}.  Make sure this is a number.  Exiting..."
+        exit 1
+    ;;
+esac
+vecho "-- PATH_TO_SCRIPT:  \"${PATH_TO_SCRIPT}\""
+if [[ ! -f ${PATH_TO_SCRIPT} ]]; then
+    echo "PATH_TO_SCRIPT not found.  Exiting..."
+    exit 1
+fi
+if [[ ! -x ${PATH_TO_SCRIPT} ]]; then
+    echo "The file pointed to by PATH_TO_SCRIPT is not executable.  Exiting..."
+    exit 1
+fi
+vecho "-- SCRIPT_USER:  \"${SCRIPT_USER}\""
+if [ -z "${SCRIPT_USER}" ]; then                    # If user unset
+    SCRIPT_USER=$(stat -c '%U' "${PATH_TO_SCRIPT}") #  use script owner
+    vecho "-- Detected user:  ${SCRIPT_USER}"
+fi
+if ! id -u "${SCRIPT_USER}" &>/dev/null; then
+    echo "The user does not exist.  Exiting..."
+fi
+vecho "-- PATH_TO_BACKUPS:  \"${PATH_TO_BACKUPS}\""
+if [[ ! -d ${PATH_TO_BACKUPS} ]]; then
+    echo "PATH_TO_BACKUPS is not a valid directory.  Exiting..."
+    exit 1
+fi
+vecho "Initial configuration variables:  OK"
+
 # Get initial count of backup files
-INITIAL_COUNT=$(sudo su ${SCRIPT_USER} -c "ls ${PATH_TO_BACKUPS}|wc -l")
+INITIAL_COUNT=$(sudo su "${SCRIPT_USER}" -c "ls ${PATH_TO_BACKUPS}|wc -l")
 vecho "Initial backup file count:  ${INITIAL_COUNT}"
 case ${INITIAL_COUNT} in
     ''|*[!0-9]*) # Make sure variable is a number
@@ -48,7 +81,7 @@ if ! [[ "${SCRIPT_RETURN}" -eq 0 ]] ; then
 fi
 
 # Get new count of backup files and check that a new one was created
-NEW_COUNT=$(sudo su ${SCRIPT_USER} -c "ls ${PATH_TO_BACKUPS}|wc -l")
+NEW_COUNT=$(sudo su "${SCRIPT_USER}" -c "ls ${PATH_TO_BACKUPS}|wc -l")
 vecho "Post-run backup file count:  ${NEW_COUNT}"
 case ${NEW_COUNT} in
     ''|*[!0-9]*) # Make sure variable is a number
@@ -65,7 +98,7 @@ fi
 while [ "${NEW_COUNT}" -gt "${BACKUP_COUNT}" ] ; do
     vecho "There are more than ${BACKUP_COUNT} files:  delete oldest file."
     # Get the list of files sorted by change date and get the last one
-    FILE_TO_DELETE=$(sudo su ${SCRIPT_USER} -c "ls ${PATH_TO_BACKUPS} --sort=time --time=ctime|tail -1")
+    FILE_TO_DELETE=$(sudo su "${SCRIPT_USER}" -c "ls ${PATH_TO_BACKUPS} --sort=time --time=ctime|tail -1")
     vecho "File to delete:  ${FILE_TO_DELETE}"
     case ${FILE_TO_DELETE} in
     ''|*[!0-9a-zA-Z._-]*) # Make sure variable uses only limited characters
@@ -80,7 +113,7 @@ while [ "${NEW_COUNT}" -gt "${BACKUP_COUNT}" ] ; do
         exit 1
     fi
     # Get the updated count
-    NEW_COUNT=$(sudo su ${SCRIPT_USER} -c "ls ${PATH_TO_BACKUPS}|wc -l")
+    NEW_COUNT=$(sudo su "${SCRIPT_USER}" -c "ls ${PATH_TO_BACKUPS}|wc -l")
     vecho "Updated backup file count:  ${NEW_COUNT}"
     case ${NEW_COUNT} in
         ''|*[!0-9]*) # Make sure variable is a number
